import time
def Paint_Logo():
    print("+------------------------------------------------+")
    time.sleep(0.05)
    print("|  _  __     _        _______                    |")
    time.sleep(0.05)
    print("| | |/ /    | |      |___  / |                   |")
    time.sleep(0.05)
    print("| | ' /_   _| |_ __     / /| |__   ___  _   _    |")
    time.sleep(0.05)
    print("| |  <| | | | | '__|   / / | '_ \ / _ \| | | |   |")
    time.sleep(0.05)
    print("| | . \ |_| | | |     / /__| | | | (_) | |_| |   |")
    time.sleep(0.05)
    print("| |_|\_\__, |_|_|    /_____|_| |_|\___/ \__,_|   |")
    time.sleep(0.05)
    print("|       __/ |                     _           _  |")
    time.sleep(0.05)
    print("|      |___/                     | |         | | |")
    time.sleep(0.05)
    print("|  _ __  _ __ ___  ___  ___ _ __ | |_ ___  __| | |")
    time.sleep(0.05)
    print("| | '_ \| '__/ _ \/ __|/ _ \ '_ \| __/ _ \/ _` | |")
    time.sleep(0.05)
    print("| | |_) | | |  __/\__ \  __/ | | | ||  __/ (_| | |")
    time.sleep(0.05)
    print("| | .__/|_|  \___||___/\___|_| |_|\__\___|\__,_| |")
    time.sleep(0.05)
    print("| | |                                            |")
    time.sleep(0.05)
    print("| |_|          Kylr Zhou Presented               |")
    time.sleep(0.05)
    print("+------------------------------------------------+")
    time.sleep(0.05)
    return
